services:
  web:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/etc/nginx/html
    ports:
      - 8080:80
    command:
      [nginx, '-g', 'daemon off;']
